import { Inter } from 'next/font/google';
import Navbar from '@/components/mui/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'TodoTrek',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" style={{ backgroundColor: 'rgb(59 130 246 / 0.5)' }}>
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
